# Generated by Django 5.1.7 on 2025-04-01 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='historiaclinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('motivo_consulta', models.TextField()),
                ('antecedentes', models.TextField()),
                ('dolor_cabeza', models.BooleanField(default=False)),
                ('dolor_muscular', models.BooleanField(default=False)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('frecuencia_ejercicio', models.IntegerField()),
                ('fecha_consulta', models.DateField(default=django.utils.timezone.now)),
                ('seguimiento', models.TextField()),
                ('perfil_paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.perfilpaciente')),
            ],
        ),
    ]
