# Generated by Django 5.1.7 on 2025-04-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_historiaclinica_perfil_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='usuario',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='perfil_paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.perfilpaciente'),
        ),
    ]
