# Generated by Django 5.1.7 on 2025-04-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_perfilpaciente_remove_historiaclinica_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='perfil_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.perfilpaciente'),
        ),
    ]
