# Generated by Django 5.1.7 on 2025-04-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_historiaclinica_perfil_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilpaciente',
            options={'verbose_name': 'Perfil Paciente', 'verbose_name_plural': 'Perfiles Pacientes'},
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='dolor_cabeza',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='dolor_muscular',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='frecuencia_ejercicio',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='peso',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='estudios_complementarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='evaluacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='obra_social',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='antecedentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='perfil_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica_set', to='aplicacion.perfilpaciente'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='seguimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
