# Generated by Django 5.1.7 on 2025-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_perfilpaciente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
