# Generated by Django 5.1.7 on 2025-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_historiaclinica_archivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
    ]
