# Generated by Django 5.1.7 on 2025-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_historiaclinica_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
